# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: push
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ yashasvichaurasia }}
          password: ${{ Yashasvi@77 }}
          repository: peterevans/dockerhub-description

      
